### ISSUE TITLE
Refreshing on 401 error

### ISSUE THREAD

**Issue by yossely** [serhiisol/ngx-auth#12]
When a request is made and returns an error (like 401) the authentication is destroyed and the app refreshes and I can not see the error on the console because of that

**Comment by serhiisol** [comment]
Hi @yossely, there's method in `AuthService` interface, which allows you to detect if request failed because of the failed authentication:
```typescript
  public refreshShouldHappen(response: HttpErrorResponse): boolean {
    return response.status === 401;
  }
```

You can check failed request properly here.

Plus, if this function returns `true` which means that request failed because of authentication,
system uses next method from the interface:
```typescript
public refreshToken(): Observable<any> {
    const refreshToken: string = localStorage.getItem('refreshToken');

    return this.http
      .post('http://localhost:3001/refresh-token', { refreshToken })
      .do(({ access_token, refresh_token }) => this.saveTokens(access_token, refresh_token))
      .catch(() => this.logout())
  }
```
This request should be successfully resolved + should update your tokens.

Another note to mention, is that `AuthInterceptor` should skip refresh request and it does it via another method:

```typescript
  public verifyTokenRequest(url: string): boolean {
    return url.endsWith('refresh-token');
  }
```

**Comment by yossely** [comment]
Ok.. then your module is great, the problem is in our api responses, we don't have the correct codes when an error occurs.

Thank you so much for your response!

**Comment by serhiisol** [comment]
No problem, good luck :D
